export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";
export const CLEAR_MAIN = "CLEAR_MAIN";
export const TOGGLE_MODAL_BUTTON_VISIBILITY = "TOGGLE_MODAL_BUTTON_VISIBILITY";
export const SET_BUTTON_CLICK_HANDLER = "SET_BUTTON_CLICK_HANDLER";
